### ISSUE TITLE
Execute Command timeout change from to 60s to Ns doesn't work

### ISSUE THREAD

**Issue by diegomontoya** [cloudradar-monitoring/rport#460] opened 2022-02-24 12:44 UTC
Version: 0.5.0 stable
Rportd OS: Ubuntu 22.04
Rport Client/Target: Ubuntu 22.04

Using rport UI to execute a command such as "sudo apt update", select multiple servers ,and changing command timeout from default 60s to 360s for example doesn't work. The commands will timeout at 60s regardless of what values are entered.

**Comment by thorstenkramm** [comment] 2022-02-28 08:23
@diegomontoya This will be fixed with the next  version 0.6.0 to be released end of February 2022.
If you like, try an update now to [0.5.20](https://github.com/cloudradar-monitoring/rport/releases/tag/0.5.20). The corresponding frontend is [Build 931](https://downloads.rport.io/frontend/development/rport-frontend-development-20220221-build-931.zip). It's just replacing the server binary and the frontend docroot.

**Closed by thorstenkramm** 2022-02-28 08:23 UTC

**Comment by dimitribellini** [comment] 2022-08-02 12:45
At the moment on 0.8.0 the timeout is working as we expect but we can not save with a different value per specific "script or command". It's by design?
Thanks

**Comment by thorstenkramm** [comment] 2022-08-03 07:25
@diegomontoya We are already working on it. With the next release, the timeout per script will be stored to the libary.

**Comment by dimitribellini** [comment] 2022-08-03 07:26
@thorstenkramm thanks so much
